services:
  db_hibernate_data:
    image: postgres:17
    container_name: db_hibernate_data
    environment:
      POSTGRES_DB: hibernate_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - hibernate_data:/var/lib/postgresql/data

volumes:
  hibernate_data:
