server:
  port: 8080
  servlet:
    context-path: /hibernate/test

spring:
  profiles:
    active: jpa

  application:
    name: HibernateWithoutSpringData

  datasource:
    url: jdbc:postgresql://localhost:5437/hibernate_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/changelog-master.xml