server:
  port: 8080
  servlet:
    context-path: /hibernate/test

spring:
  application:
    name: HibernateWithoutSpringData
  datasource:
    url: jdbc:postgresql://localhost:5437/hibernate_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: PostgreSQLDialect
        format_sql: true